[package]
name = "shiguredo_rtmp"
version = "2026.1.0-canary.5"
edition = "2024"
rust-version = "1.88"
authors = ["Shiguredo Inc."]
license = "Apache-2.0"
description = "RTMP library"
homepage = "https://github.com/shiguredo/rtmp-rs"
repository = "https://github.com/shiguredo/rtmp-rs"
readme = "README.md"

[features]
# これを有効にすると PBT / fuzzing で必要な構造体などが外部に公開されるようになる
pbt = []

[dependencies]

[workspace]
members = ["crates/c-api", "examples/publish", "examples/server", "pbt"]
exclude = ["fuzz"]
